version: 2
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/elixir:1.8.1
      environment:
        MIX_ENV: test
        CODECOV_TOKEN: fa53a02b-c3e8-4abc-b405-8df6e543c868
    - image: circleci/postgres
      environment:
        POSTGRES_USER: postgres

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-cache-{{ checksum "mix.lock" }}
            - v1-deps-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - save_cache:
          key: v1-deps-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .mix

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)

  credo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run credo
          command: mix credo --strict

  check_formatted:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Verify formatted
          command: mix format --check-formatted
  static_security_checks:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Sobelow
          command: mix sobelow --config
  dialyzer:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-plt-cache-{{ checksum "mix.lock" }}
            - v1-plt-cache
      - run: mix dialyzer --plt
      - save_cache:
          key: v1-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix
      - run:
          name: Run dialyzer
          command: mix dialyzer --halt-exit-status
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "LAUNCH"
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate Docs
          command: mix docs -f epub
      - run:
          name: Generate Docs
          command: gem install sendgrid-ruby
      - run:
          name: "SendDocs"
          command: ruby scripts/email_docs.rb
workflows:
  version: 2
  continuous_integration:
    jobs:
      - build
      - test:
          requires:
            - build
      - check_formatted:
          requires:
            - build
      - credo:
          requires:
            - build
      - dialyzer:
          requires:
            - build
      - static_security_checks:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
            - credo
            - dialyzer
            - check_formatted
            - static_security_checks
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
      - docs:
          requires:
            - deploy
